<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>RoSharp</PackageId>
    <Title>RoSharp</Title>
    <Version>2.0.0-alpha7</Version>
    <Authors>Thunder300</Authors>
    <Company>None</Company>
    <Description>RoSharp is a feature-rich wrapper API for Roblox's Web API.</Description>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <RepositoryUrl>https://github.com/Thundermaker300/RoSharp</RepositoryUrl>
    <PackageIcon>RobloxCSVersion2.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageTags>roblox;api;wrapper;c#;webapi</PackageTags>
    <NeutralLanguage>en-US</NeutralLanguage>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageReleaseNotes>See https://github.com/Thundermaker300/RoSharp/releases/tag/v2.0.0-alpha7
      for release notes.</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="RobloxCS.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="RobloxCSVersion2.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>